# GET ALL USER
GRAPHQL http://localhost:3001/graphql

query GET_ALL {
   findAll {
   id,
    name,
    document,
    phones {
       number
     },
    birthDate,
    addresses
  }
}

###
# GET ONE USER BY ID
GRAPHQL http://localhost:3001/graphql

query GET_ONE_BY_ID {
  user(id: 2) {
    name,
    id,
    phones {
      number
    }
  }
}

###
# SAVE USER
GRAPHQL http://localhost:3001/graphql

mutation SAVE {
  createUser(createUserInput: {
    name: "Dona Maria",
    document: "123456",
    phones: [
          {
            number: "991461174",
            areaCode: "67",
            countryCode: "+55"
          }
        ],
    birthDate: "1986-01-01",
    addresses: [
          "123 Main St, CityA",
          "456 Elm St, CityB"
        ]
  }) {
    id,
    name,
    document,
    phones {
       id,
       number
    }
  }
}

###
# UPDATE USER
GRAPHQL http://localhost:3001/graphql

mutation UPDATE {
  updateUser(id: "2", updateUserInput: {
    name: "Don Julio",
    document: "123456",
    phones: [
          {
             areaCode: "65"
             countryCode: "+55",
             number: "991461174"
          }
        ],
    birthDate: "1986-01-01",
    addresses: [
          "123 Main St, CityA",
          "456 Elm St, CityB"
        ]
  }) {
    id,
    name,
    document,
    phones {
      number,
      areaCode
    }
  }
}


###
# DELETE USER
GRAPHQL http://localhost:3001/graphql

mutation DELETE {
  removeUser(id: "2")
}