### GET request with a header
GET http://localhost:3001/user
Accept: application/json

### GET request with a header
GET http://localhost:3001/user/1
Accept: application/json

### Send POST request with json body
POST http://localhost:3001/user
Content-Type: application/json

{
  "name": "John MARIA ",
  "document": "123456789",
  "birthDate": "1990-01-01",
  "phones": ["123-456-7890", "987-654-3210"],
  "addresses": ["123 Main St, CityA", "456 Elm St, CityB"]
}


### Send POST request with json body
PUT http://localhost:3001/user/1
Content-Type: application/json

{
  "name": "John MARIA 1",
  "document": "123456789",
  "birthDate": "1990-01-01",
  "phones": ["123-456-7890", "987-654-3210"],
  "addresses": ["123 Main St, CityA", "456 Elm St, CityB"]
}


### DELETE request with a header
DELETE http://localhost:3001/user/1
Accept: application/json
