### GET request with a header
GET http://localhost:3000/user
Accept: application/json

### GET request with a header
GET http://localhost:3000/user/1
Accept: application/json

### Send POST request with json body
POST http://localhost:3000/user
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### Send POST request with json body
PATCH http://localhost:3000/user/1
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

### DELETE request with a header
DELETE http://localhost:3000/user/1
Accept: application/json
