### GET ALL
GET http://localhost:3001/api/user
Accept: application/json

### GET BY ID
GET http://localhost:3001/api/user/1
Accept: application/json

### SAVE
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "name": "John MARIA ",
  "document": "123456789",
  "birthDate": "1990-01-01",
  "phones": ["123-456-7890", "987-654-3210"],
  "addresses": ["123 Main St, CityA", "456 Elm St, CityB"]
}


### UPDATE
PUT http://localhost:3001/api/user/1
Content-Type: application/json

{
  "name": "John MARIA 1",
  "document": "123456789",
  "birthDate": "1990-01-01",
  "phones": [
    {
      "areaCode": "65",
      "countryCode": "+55",
      "number": "991461174"
    }
  ],
  "addresses": [
    "123 Main St, CityA",
    "456 Elm St, CityB"
  ]
}


### DELETE
DELETE http://localhost:3001/api/user/1
Accept: application/json
